### ISSUE TITLE
安装cell，没有出现cell文件夹

### ISSUE THREAD

**Issue by sjkgames** [project-nano/releases#1]
我使用一台KVM虚拟机安装Nano，但是在安装cell的时候，安装完了但是没有cell这个文件夹，请教是不是缺少什么依赖？

**Comment by bokuore** [comment]
请看一下最初选择安装模块的时候没有正确输入，如果要安装所有模块，一定要正确输入“0,1,2"或者使用0.9.1输入”3“选择全部安装；
同时可以观察installer日志，安装过程中是否出现Cell模块安装信息，如果没有的话，多半就是模块选择错误导致的

**Comment by bokuore** [comment]
没有更新反馈，问题先关闭了~
