### ISSUE TITLE
关于不同局域网服务发现的问题

### ISSUE THREAD

**Issue by laikee99** [project-nano/releases#11]
你好，首先表达我对nanos的方便顺滑表示赞扬！
然后想请教一下，如果异地集群管理，nanos支持gre隧道设备做广播吗？另外是否支持服务中转呢？

**Comment by laikee99** [comment]
组建了GRE内网后报错：
start service fail: query timeout

**Comment by bokuore** [comment]
网络管理我不熟，配置方式可能要自己研究，要满足两个条件
1、组播消息能够互通，比如上面这个报错就是组播查询收不到响应导致的
2、宿主机ip之间能够互相通讯

**Comment by laikee99** [comment]
> 网络管理我不熟，配置方式可能要自己研究，要满足两个条件
> 1、组播消息能够互通，比如上面这个报错就是组播查询收不到响应导致的
> 2、宿主机ip之间能够互相通讯

谢谢大佬，我有点希望改成指定主机的形式。。。
虽然sonar很好用，但是对于异地集群的管理十分不便，我会测试一下是否是组网不支持UDP multicast，但multicast已经设置开放了。

**Comment by bokuore** [comment]
> > 网络管理我不熟，配置方式可能要自己研究，要满足两个条件
> > 1、组播消息能够互通，比如上面这个报错就是组播查询收不到响应导致的
> > 2、宿主机ip之间能够互相通讯
> 
> 谢谢大佬，我有点希望改成指定主机的形式。。。
> 虽然sonar很好用，但是对于异地集群的管理十分不便，我会测试一下是否是组网不支持UDP multicast，但multicast已经设置开放了。

因为最开始设计里面考虑到机房机器多了之后，经常会迁移或者维护修改地址之类的需求，为了避免每次运维手工配置地址产生错误，所以使用了自动动态发现和组网，这个属于nano的基础设计之一，要动的话只能自己fork一个实现了

**Comment by laikee99** [comment]
> > > 网络管理我不熟，配置方式可能要自己研究，要满足两个条件
> > > 1、组播消息能够互通，比如上面这个报错就是组播查询收不到响应导致的
> > > 2、宿主机ip之间能够互相通讯
> > 
> > 
> > 谢谢大佬，我有点希望改成指定主机的形式。。。
> > 虽然sonar很好用，但是对于异地集群的管理十分不便，我会测试一下是否是组网不支持UDP multicast，但multicast已经设置开放了。
> 
> 因为最开始设计里面考虑到机房机器多了之后，经常会迁移或者维护修改地址之类的需求，为了避免每次运维手工配置地址产生错误，所以使用了自动动态发现和组网，这个属于nano的基础设计之一，要动的话只能自己fork一个实现了

感谢大佬，我也是这样打算的，我想改成内网dns的形式或者使用etcd来达到这一点。

**Comment by sddwt** [comment]
d
![image](https://user-images.githubusercontent.com/28212423/126029050-193c3181-4e85-4416-b45e-75939ff9bfc8.png)
