### ISSUE TITLE
请问Nano有计划支持超融合（HCI）吗？

### ISSUE THREAD

**Issue by ejzhang** [project-nano/releases#13]
首先感谢提供这么优质的云平台系统！
Nano貌似不支持超融合（HCI），看文档好像只支持以Cell为单位进行资源调度，如果能将所有Cell的计算、存储资源统一管理，就更好了。

**Comment by bokuore** [comment]
没有哟

就算本地调度也有不少坑，超融合还涉及网络调度时延一堆东西，对于一个免费软件要求太高了~

**Comment by ejzhang** [comment]
多谢，现在用着ZStack免费版，看Nano不错想尝试一下，就怕遇坑:D
