### ISSUE TITLE
关闭和重启云主机失败

### ISSUE THREAD

**Issue by wjangelking** [project-nano/releases#2]
**关闭云主机操作**

![image](https://user-images.githubusercontent.com/17584830/59149729-c8598100-8a4b-11e9-80aa-d7c922a386d1.png)

**重启云主机操作（非强制）**
![image](https://user-images.githubusercontent.com/17584830/59149736-ed4df400-8a4b-11e9-961b-98902a8f9226.png)

**手动关闭也无效**
![image](https://user-images.githubusercontent.com/17584830/59149763-6a796900-8a4c-11e9-9c77-d715902bcb32.png)

**Comment by bokuore** [comment]
云主机OS？是否安装相应的服务？

非强制关机只是向虚拟机发送，但是实际服务由虚拟机操作系统处理，比如CentOS云主机就需要安装acpid服务才能正常关机

**Comment by bokuore** [comment]
超过30天没有更新，进行关闭
