### ISSUE TITLE
用户权限策略问题

### ISSUE THREAD

**Issue by wjangelking** [project-nano/releases#3]
同一个用户组下的用户，看不到其他用户创建的云主机

**Comment by bokuore** [comment]
不能，目前限制只能看到相同用户的云主机

因为组权限不同用户会有不同需求，所以后续版本会让提供一个独立功能，由用户设置符合需要的组内资源管理策略

**Comment by bokuore** [comment]
最新版本已经可以通过设置组资源可见性，允许访问同一组内其他用户创建的资源了
