### ISSUE TITLE
本地存储不能自定义路径

### ISSUE THREAD

**Issue by wjangelking** [project-nano/releases#4]
默认的本地存储不能修改路径，建议增加修改路径功能

**Comment by bokuore** [comment]
这个主要是考虑产品简单性设计的，另外一部分原因也是libvirt的默认存储路径还涉及到selinux权限设置

目前版本可以通过挂载其他设备到libvirt存储路径，或者1.0代码开放后修改Cell代码实现

**Comment by bokuore** [comment]
1.2.0已经新增修改存储路径功能
