### ISSUE TITLE
云主机操作重装系统后系统盘会被删除

### ISSUE THREAD

**Issue by wjangelking** [project-nano/releases#5]
云主机操作重装系统后，系统盘会被删除

![image](https://user-images.githubusercontent.com/17584830/59158142-8b8f9780-8ae8-11e9-91d9-d870b4fcaab2.png)

重装系统的过程中查看系统盘存在，系统重装完成之后再查看系统盘不存在

![image](https://user-images.githubusercontent.com/17584830/59158122-3e132a80-8ae8-11e9-8d42-d73ea41508a8.png)

**Comment by bokuore** [comment]
请检查下core/cell的日志，在重置过程是否发生了其他操作或者异常导致
另外使用的是什么存储

**Comment by bokuore** [comment]
超过30天没有更新，进行关闭
