### ISSUE TITLE
上传镜像就挂了

### ISSUE THREAD

**Issue by bwcxyk** [project-nano/releases#7]
![image](https://user-images.githubusercontent.com/28802427/78093177-379dc880-7404-11ea-925e-3f4fb744981b.png)

**Comment by bokuore** [comment]
看下后台core的报错，是不是中间出现了网络中断

**Comment by bwcxyk** [comment]
> 看下后台core的报错，是不是中间出现了网络中断

![image](https://user-images.githubusercontent.com/28802427/78093422-c01c6900-7404-11ea-93bc-0736ce971c7c.png)

**Comment by bokuore** [comment]
创建镜像之后还没上传数据就直接收到了删除指令，那么多半是开始上传的过程出错了，触发了回撤。用chrome调试模式的network面板，看看上传数据的报文是不是出错了

**Comment by bokuore** [comment]
1.2.0已经修复该问题
